export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_LOAN_LIST = 'SET_LOAN_LIST'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_STATE_PERSONAL_DATA = 'SET_STATE_PERSONAL_DATA'

export const SET_SEARCH_FULL_SCREEN = 'SET_SEARCH_FULL_SCREEN'

export const SET_USER_INFO = 'SET_USER_INFO'

export const SET_CHOICE_SHOW_ONE = 'SET_CHOICE_SHOW_ONE'

export const SET_CHOICE_SHOW_TWO = 'SET_CHOICE_SHOW_TWO'

export const SET_CHOICE_SHOW_THREE = 'SET_CHOICE_SHOW_THREE'

export const SET_CHOICE_SHOW_FOUR = 'SET_CHOICE_SHOW_FOUR'

export const SET_STATE_PHOTO = 'SET_STATE_PHOTO'

export const SET_STATE_COMMUNIC = 'SET_STATE_COMMUNIC'

export const SET_STATE_BANK_CARD = 'SET_STATE_BANK_CARD'

export const SET_ADD_BANK_CARD = 'SET_ADD_BANK_CARD'

export const SET_ID_VALIDATE = 'SET_ID_VALIDATE'

export const SET_CHOICE_SHOW_MIAO = 'SET_CHOICE_SHOW_MIAO'
